font_family      JetBrainsMono Nerd Font
font_size        11.0
window_padding_width 2
background_opacity 0.85
confirm_os_window_close 0

# Endeavour Colors
foreground #a9b1d6
background #1a1b26
color4  #7f7fd5
color5  #ff79c6
